# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 613b82f849f5ef8853d7571f61454b7d8cc4305e651d20fc5022712954b101028a1e65f2986c92ade2c47736248e9b01ca78c913bda81d4aee9ff0b2059c117b

test:
  secret_key_base: 88c002b5b36f032e531a4509c1c7bc8bc874c08e429a56d696528bc04b5dc142920d1889427bae68f6286c69fa87a5a593fedf83bf4321365864f9339bf07321

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
